### ISSUE TITLE
Should .lock files be under version control?

### ISSUE THREAD

**Issue by walice** [walice/skyshares#3]
You have pushed `yarn.lock` in the new branch [SKY-1-admin-fix](https://github.com/walice/skyshares/tree/SKY-1-admin-fix).

When I pull from the remote and run `npm install` to update my node modules, this changes my `yarn.lock` file and shows up as a change in my Git working directory.

Should `yarn.lock` be added to `.gitignore`?

Relates to  #[SKY-2 Refactor codebase](https://skyshares.atlassian.net/jira/software/projects/SKY/boards/2/roadmap?selectedIssue=SKY-2).

**Comment by Caleb-Oneyemi** [comment]
No. The lock file shouldn't be added to .gitignore.

It should always be committed.

The lock file helps to deterministically build dependencies in node_modules hence in a way solving the `it works on my machine` problem.

**Comment by walice** [comment]
OK.
When I run `npm install`, it changes both `yarn.lock` and `package-lock.json` in my working directory and shows up as changes to be committed. Even though I should have the latest version of the packages.

I tested this by discarding the local changes to the two files above and running `npm install` again --> still leads to changes in the lock files.

I understand that we shouldn't be running `npm install` every single time we serve up SkyShares, but I don't understand the logic of having a lock file under version control if the lock file changes on each collaborator's local machine.

See sample diff for `yarn.lock`: it looks like it is just changing the order of _version_, _integrity_, and _resolved_ lines without making substantive changes.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/5657377/233489439-1028803a-27f9-4542-99d3-ea5a319f8ffc.png">

Likewise, `package.json` just looks it is being regenerated at every `npm install`.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/5657377/233489995-4e1c4b77-bb15-457a-8a59-395f76075e76.png">

So, is it correct to say that **even if I pushed these files to the repo, it wouldn't change anything substantive on your local machine** the next time you run a `git pull`? 🤔 Just trying to understand best practices in developing a node.js app collaboratively.

**Comment by Caleb-Oneyemi** [comment]
Typically, a team uses one package manager. Most likely either NPM or Yarn. NPM has its lock file called package-lock.json while the yarn lock file is called yarn.lock. Running NPM install does create the package-lock (if not already existing) and update the yarn-lock but you would normally use only one package manager.

Also, to avoid unnecessarily changing the lock file while in development, after pulling latest changes from your teammates, you could check changes in the package.json file and install those individual dependecies with something yarn add express@4.0.0 or npm install express@4.0.0 or uninstall them if they were removed.

Another thing people do is install exact dependencies by having values in their package.json like express: "4.0.0" instead of express: "~4" or express: "*". If the versions in package.json are not exact, running npm install or yarn may pull higher versions of dependencies like a patch upgrade or minor upgrade depending on how they are specified in the package.json file. This will also end up changing the lock file.

So to recap, if the Team doesn't use exact dependencies in the package.json file, you would manually install new individual dependencies (or remove deleted dependencies) when you get changes from teammates in the package.json file. If they do use exact dependencies, you can safely run npm install or yarn.

As for deployments, running npm ci or yarn install --frozen-lockfile has the same safe effect. With all this in place, everybody on the team uses the exact same dependencies and those same dependencies are used in the production environment. No dependency mismatch.

On a side note, most changes to lock files wouldn't matter for minor upgrades and patch fixes in dependencies. Ideally, those upgrades shouldn't introduce breaking changes in a dependency but you can't exactly guarantee so it's good to be safe.
